channels:
  - conda-forge
dependencies:
  - python==3.5
  - sphinx>=1.4
  - pandoc
  - nbconvert
  - ipykernel
  - numpy
  - pip:
    - nbsphinx
    - "--editable=git+https://github.com/bitprophet/releases/#egg=releases"